name: Package

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install --ignore-scripts

    - name: Build Source
      run: npm run build

    - name: Package TGZ
      run: npm pack

    - name: Archive Artifacts
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: '*.tgz'
